kind: pipeline
volumes:
  - name: cache
    host:
      path: /root/.m2
  - name: ssh_keys
    host:
      path: /root/.ssh
clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    volumes:
      - name: ssh_keys
        path: /root/.ssh
    environment:
      warehouse_name: blog-server
      publish_branch: drone

    commands:
      - echo $publish_branch
      - echo $DRONE_GIT_SSH_URL
      - ls /root/.ssh/
      - chmod -R 600 /root/.ssh/
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - git clone -b $publish_branch --depth=1 $DRONE_GIT_SSH_URL
      - cd $warehouse_name
      - pwd
      - mv -f * .[^.]* /drone/src
      - ls

  - name: build
    image: maven:3.6.3-jdk-11
    depends_on: [clone]
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package -DskipTests=true
  - name: deploy
    image: appleboy/drone-scp
    depends_on: [build]
    settings:
      host:
        from_secret: host
      port: 22
      username:
        from_secret: username
      password:
        from_secret: password
      target: /root/blog-server
      source: ./target/blog-server-1.0.0.jar
